version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rbw-air-quality-pub-cw-data"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17nku8mms85o9"
s3_prefix = "rbw-air-quality-pub-cw-data"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
