AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  air_quality publish CW events lambda

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  rbwPublishPollutionData:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: rbw_air_pollution_pub_cw_data
      CodeUri: ./pub_cw_data/
      Handler: handler.lambda_handler
      Runtime: python3.9
      Policies:
      - CloudWatchPutMetricPolicy: {}

  rbwPublishPollutionDataLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: rbwPublishPollutionData
    Properties:
      LogGroupName: !Sub "/aws/lambda/${rbwPublishPollutionData}"
      RetentionInDays: 7    

  iotInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref rbwPublishPollutionData
      Action: lambda:InvokeFunction
      Principal: iotanalytics.amazonaws.com

  pollutionDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties: 
      DashboardName: rbwPublishPollutionDashboard
      DashboardBody: >
        {
            "widgets": [
                {
                    "height": 12,
                    "width": 24,
                    "y": 0,
                    "x": 0,
                    "type": "metric",
                    "properties": {
                        "view": "timeSeries",
                        "stacked": false,
                        "metrics": [
                            [ "rbw/air/pollution01", "pmten", { "label": "10μm" } ],
                            [ ".", "pmtwofive", { "yAxis": "right", "label": "2.5μm" } ]
                        ],
                        "region": "us-east-1",
                        "title": "Particulate matter (PM) concenration",
                        "period": 300,
                        "legend": { "position": "right" },
                        "yAxis": {
                            "left": { "label": "10μm", "showUnits": false },
                            "right": { "showUnits": false, "label": "2.5μm" }
                        }
                    }
                }
            ]
        }